In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder,StandardScaler
import seaborn as sns
import matplotlib as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.linear_model import LogisticRegression
import pickle

def get_clean_data():
    data=pd.read_csv("weather_classification_data.csv")
    label_encoder=LabelEncoder()
    data["Cloud Cover"]=label_encoder.fit_transform(data["Cloud Cover"])
    data["Season"]=label_encoder.fit_transform(data["Season"])
    data["Location"]=label_encoder.fit_transform(data["Location"])
    data["Weather Type"]=label_encoder.fit_transform(data["Weather Type"])
    return data

def create_model(): 
    data=get_clean_data()
    X=data.drop(["Weather Type"],axis=1)
    y=data["Weather Type"]

    scaler=StandardScaler()
    X=scaler.fit_transform(X)

    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=42)
    model=LogisticRegression(multi_class="multinomial")
    model.fit(X_train,y_train)

    

    y_pred = model.predict(X_test)
    print('Accuracy of our model: ', accuracy_score(y_test, y_pred))
    print("Classification report: \n", classification_report(y_test, y_pred))
    print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred))
    return model,scaler

def main():
    data=get_clean_data()
    model,scaler=create_model()

    with open("model.pkl","wb") as f:
        pickle.dump(model,f)
    with open("scaler.pkl","wb") as f:
        pickle.dump(scaler,f)

if __name__=="__main__":
    main()

E:\GENAI\Llama_index\venv\lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


Accuracy of our model:  0.8497474747474747
Classification report: 
               precision    recall  f1-score   support

           0       0.81      0.82      0.81       955
           1       0.84      0.85      0.85       982
           2       0.88      0.94      0.91      1033
           3       0.87      0.79      0.83       990

    accuracy                           0.85      3960
   macro avg       0.85      0.85      0.85      3960
weighted avg       0.85      0.85      0.85      3960

Confusion Matrix: 
 [[780  85  31  59]
 [ 42 835  72  33]
 [ 32  10 968  23]
 [113  64  31 782]]
